name: flutter_login
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  flutter_bloc: ^8.1.2
  formz: ^0.5.0+1
  equatable: ^2.0.5
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
